[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "public"

[context.production.environment]
  FLUTTER_VERSION = "3.22.1"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
